feat: audio support
yondonfu/comfystream pull request #10
Opened 2024-12-13 18:57 UTC by varshith15

2024-12-13 20:24 UTC, yondonfu commented
Thanks for the PR! A couple requests:

1. Please provide a high level overview of the changes and expected behavior which will make review easier.
2. Please rebase off the latest main as resolving the conflicts will make review easier.

2024-12-14 19:27 UTC, varshith15 commented
@yondonfu it was supposed to be a draft PR (have to try to plug in the UI part, rebase changed a bunch of things), my bad

2024-12-21 17:09 UTC, UD1sto commented
Hey @varshith15 ! I am very interested in contributing to your efforts for audio support. Would you like to discuss and coordinate?

2024-12-21 19:26 UTC, varshith15 commented
hey @UD1sto, yes ofcourse, please find me on discord, let's discuss on there

2025-02-06 20:08 UTC, eliteprox requested changes
Thanks for this amazing feature @varshith15! I tested this successfully with an audio-only stream after making a few necessary changes. I re-based the branch and pushed it to `audio_support_main` for easier review, see https://github.com/yondonfu/comfystream/compare/audio_support_main?expand=1.

Please see the review comments below and rebase (or force push from 598ed4e1764f149f84fd2e4fece0eb73f1261521), then re-request review when ready

2025-02-06 20:12 UTC, varshith15 commented on src/comfystream/client.py
> +        self.comfy_client = EmbeddedComfyClient(config, max_workers=max_workers)
it's used here https://github.com/hiddenswitch/ComfyUI/blob/ef74b9fdda4587421a5f5bdfa81cbbce31b8c530/comfy/client/embedded_comfy_client.py#L157

2025-02-06 20:14 UTC, varshith15 commented on nodes/audio_utils/pitch_shift.py
> +        shifted_audio = librosa.effects.pitch_shift(audio_float, sample_rate, n_steps=pitch_shift)
will clean this up for the final commit, this node shouldn't be part of comfystream, ill move it elsewhere

2025-02-06 20:14 UTC, varshith15 commented on src/comfystream/client.py
> +        for idx in range(self.current_prompts):
yes, this is a mistake, should be a list

2025-02-06 20:15 UTC, varshith15 commented on ui/src/components/settings.tsx
>        await navigator.mediaDevices.getUserMedia({ video: true });
makes sense

2025-02-06 20:16 UTC, varshith15 commented on src/comfystream/client.py
> +        self.comfy_client = EmbeddedComfyClient(config, max_workers=max_workers)
to run multiple comfyui prompts concurrently in separate threads

2025-02-06 20:29 UTC, eliteprox commented on src/comfystream/client.py
> +        self.comfy_client = EmbeddedComfyClient(config, max_workers=max_workers)
I see it's passed directly, what does `max_workers` do? Do we require `max_workers`  to be greater than 1 in order to do both video and audio simultaneously? In the [README](https://github.com/hiddenswitch/ComfyUI?tab=readme-ov-file#command-line-arguments) I see the term `worker` is used in a distributed worker queue context, which we don't currently use.

2025-02-06 20:40 UTC, varshith15 commented on src/comfystream/client.py
> +        self.comfy_client = EmbeddedComfyClient(config, max_workers=max_workers)
in the version that we use in comfystream creates a thread pool executor to run concurrent asyncio threads

```
self._executor = executor or ThreadPoolExecutor(max_workers=max_workers)
```

2025-02-06 20:55 UTC, eliteprox commented on src/comfystream/client.py
> +        self.comfy_client = EmbeddedComfyClient(config, max_workers=max_workers)
I noticed that too, so it looks like this does produce async workers even when a distributed queue is not used.

2025-02-06 20:57 UTC, varshith15 commented on src/comfystream/client.py
> +        self.comfy_client = EmbeddedComfyClient(config, max_workers=max_workers)
yes

2025-02-07 16:16 UTC, eliteprox commented
The audio streaming works great, but while testing video, there was an async or race-condition type of issue with tensor_utils. Remarkably, the async worker queue creates a frame-skipping effect (which is desired). See attached stack trace.
 
[message(13).txt](https://github.com/user-attachments/files/18709308/message.13.txt)

2025-02-17 17:16 UTC, varshith15 commented on src/comfystream/client.py
> +        # TODO: Need to handle cleanup for EmbeddedComfyClient if not using async context manager?
done, please check https://github.com/yondonfu/comfystream/pull/10/commits/a685e111c1e0934cd741f221c36489877055ae99

2025-02-17 20:23 UTC, eliteprox approved these changes
Thank you for your contribution @varshith15! I've fully tested this change with audio support. This change also implements frame skipping for video workflows. There is only one issue remaining related to simultaneous audio/video inference. Currently users may run an audio or video workflow, but not both at the same time. This is in scope to be resolved following the hiddenswitch version upgrade https://github.com/yondonfu/comfystream/pull/37

2025-02-17 22:37 UTC, merged

2025-02-18 13:49 UTC, rickstaa commented
@eliteprox Thanks a ton for reviewing and merging this! 🙌  

Just a small request for next time—would it be possible to use a combined commit message when squashing? The individual commit history is already in the pull request, and having a single message would make it much easier to navigate, especially in the terminal.  

Thanks again!

2025-02-18 15:19 UTC, eliteprox commented
> @eliteprox Thanks a ton for reviewing and merging this! 🙌
> 
> Just a small request for next time—would it be possible to use a combined commit message when squashing? The individual commit history is already in the pull request, and having a single message would make it much easier to navigate, especially in the terminal.
> 
> Thanks again!

Thank you for the feedback, this PR was having several UI conflicts as it aged. I used a squash commit to re-base and squash the commits before squashing again to main. Apologies for the long commit message, I'll be mindful about that going forward.